### ISSUE TITLE
Policy Mappings

### ISSUE THREAD

**Issue by fpreti** [lucafaggianelli/sails-hook-bucaniere#7]
Hi,
i'm a newbie of sails, i tried to use the admin panel that you have develop, i think that missing the management of policy mapping.
An example:
sails config/policies.js -> try to add entry admin/*': 'is-logged-in, but not working.

Do you have any idea to resolve this?

thank you

**Comment by fpreti** [comment]
I see fork https://github.com/gorgueugr/sails-hook-bucaniere which implements this functionality
@lucafaggianelli can you merge into master this changes?

**Comment by lucafaggianelli** [comment]
Ah yes, I wanted to implement this on the app side rather than inside the hook, but I never did. I don't have a solution now, sorry but I'm not developing this hook anymore, actually, I abandoned Sails for other frameworks!

Anyway, if @gorgueugr wants to submit a pull request I'm more than happy to merge his code.

**Comment by fpreti** [comment]
Thank you Luca for the answer, i will try to develop a new hook.
Anyway which frameworks using now?

**Comment by lucafaggianelli** [comment]
Yeah Francesco, you can fork this one as a template and make your admin panel, I remember that it wasn't straightforward to create the base logic for such kind of hook (init, register route with views, etc.)

Now I mostly use Firebase, though when I need a real back-end I use Koa, which is the successor of Express, you almost start from scratch and that seems scary, but just add some plugins and you have everything.
Other frameworks I used and liked:
* Hackathon Starter, the most famous Node template/boilerplate (that is, you clone the repo, don't install the package from NPM) https://github.com/sahat/hackathon-starter
* HapiJS, probably a bit dated now, but I think is still a good option
* AdonisJS, quite young, but I like it's architecture and seems very promising

I used Sails only for 1 project and I regret it every day! In the beginning, it seems nice as everything works out of the box, but the truth is that you don't have any control over the framework, many things are done behind the scenes, they integrated Vue via their custom plugin, even to manage automatic deployments I had to do some tricks. I could write a poem about things I don't like in Sails, sorry :D I hope this is useful to you!

**Comment by fpreti** [comment]
Thank you for your suggestion
